#!/bin/bash
set -e

TARGET_DIR="${TARGET_DIR:-$HOME}"
if [ ! -d "$TARGET_DIR" ]; then
    echo "The target directory "$TARGET_DIR" does not exist."
    exit 1
fi

# Gather the files to be installed into $TARGET_DIR.
# The files are in the dotfiles/ directory,
# and the list of files to be installed is the FILES variable.
SCRIPT_DIR="$(dirname $0)"
FILES="$SCRIPT_DIR"/dotfiles/*
if [ -z "$FILES" ]; then
    echo "No files to install."
    exit 0
fi
echo "Files to be installed:"
column -ts'->' <(for FILE in $FILES; do
    echo "$FILE -> $TARGET_DIR/.$(basename $FILE)"
done)

# Ask the user for confirmation before installing the files.
read -p "Do you want to install these files? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 1
fi

# If a file in the $FILES already exists in $TARGET_DIR, move it to the backup directory.
# If the backup directory does not exist, create it.
# If a file already is backed up, overwrite it.
BACKUP_DIR="$TARGET_DIR/.dotfiles_backup"
for FILE in $FILES; do
    if [ -e "$TARGET_DIR/.$(basename $FILE)" ]; then
        if [ ! -d "$BACKUP_DIR" ]; then
            mkdir -vp "$BACKUP_DIR"
        fi
        mv -v "$TARGET_DIR/.$(basename $FILE)" "$BACKUP_DIR/$(basename $FILE)"
    fi
done

# Install the files by creating symbolic links in $TARGET_DIR.
for FILE in $FILES; do
    ln -sv "$(realpath $FILE)" "$TARGET_DIR/.$(basename $FILE)"
done
