export SOURCED=".bash_aliases:$SOURCED"

# Screen shortcuts
alias s=screen
alias sl="s -ls"
alias ss="s -S"
alias sr="s -r"
alias sR="s -D -R"

# Modify the default values for builtins
alias grep="grep --color=auto"
alias ls="ls -CFG --color=auto"
alias mkdir="mkdir -pv"
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

# Dump clipboard contents to stdout
alias paste="xclip -selection clipboard -o"

# Shortcut to update and upgrade linux distributions
alias aptuu="sudo apt -y update && sudo apt -y upgrade"

# Search for an expression in directory and children
alias contains="grep -rnw . -e"

# Shortcut for opening the default editor
alias e="$EDITOR"
# Shortcuts to edit specific files
alias evim="e ~/.vimrc"
alias envim="e ~/.config/nvim/init.lua"
alias erc="e ~/.bashrc && source ~/.bashrc"
alias ealias="e ~/.bash_aliases && source ~/.bash_aliases"
etmp() { e "$(mktemp)$1"; }

# Git shortcut
alias gs="git status"
alias gv="git remote -v"
alias gb="git branch"
alias gd="git diff"
alias gcam="git commit -am"

# Python
alias py="python3"
alias ipy="ipython"
alias m="python3 -m"
alias p="poetry"
alias jn="jupyter notebook"
alias tb="tensorboard --logdir ."
alias va="source .venv/bin/activate"

# Shortcut to make new dir and cd into it
md() {
    mkdir -p "$@" && cd "$@";
}

# Create executable bash script and edit it
# The first argument as the path to the script file that will be created
cmd() {
    local NAME="${1:?'Usage: cmd <cmdname>'}"
    if [ -e "$NAME" ]; then
        echo "Command already exists: $NAME" >&2
        return 1
    fi
    echo "Creating command: $NAME"
    echo '#!/bin/bash' >> "$NAME"
    vim "$NAME"
    chmod +x "$NAME"
}

# Append a new note to the notes file
note() {
    # If ~/notes.txt last modified day was yesterday, append a clear separator with the date before appending the note's content
    touch ~/notes.txt
    if [ $(date -r ~/notes.txt +%Y%m%d) -e $(date -d "yesterday" +%Y%m%d) ]; then
        echo -e "

$(date +%Y-%m-%d)

" >> ~/notes.txt
    fi
    echo "$@" >> ~/notes.txt
}

# Open the notes file
notes() {
    cat ~/notes.txt
}

# Tail a file and log the changes by prefixing them with the date of the change
taildate() {
    tail -f "$1" | xargs -IL date +"%Y-%m-%d %H:%M:%S L"
}
