# ~/.bash_profile: executed by bash(1) for login shells.

# Mark bash profile as sourced
export SOURCED="$BASH_SOURCE:$SOURCED"

# Load golang
[ -d "/usr/local/go/bin" ] && export PATH="$PATH:/usr/local/go/bin/"

# Load nodejs and npm
[ -d "/usr/local/node/bin" ] && export PATH="$PATH:/usr/local/node/bin/"

# Set the npm package install dir
if command -v npm &> /dev/null; then
    export NPM_PREFIX="$HOME/.local/npm"
    if [ ! "$(npm config get prefix)" == "$NPM_PREFIX" ]; then
        echo "npm is installed: Setting install directory to $NPM_PREFIX" >&2
        npm config set prefix "$NPM_PREFIX"
    fi
    export PATH="$(npm config get prefix)/bin:$PATH"
    export PATH="./npm_modules/bin:$PATH"
fi

[ -d "$LOCAL/bin" ] && export PATH="$LOCAL/bin:$PATH"

# In case some non-bash stuff gets added, link .bash_profile to .profile
# Load .profile first, because it is basically an alias for .bash_profile
[ -f ~/.profile ] && source ~/.profile

# Load the machine-local .bash_profile
# Load local .bash_profile last because neither of the other two should depend on anything in here
[ -f "$LOCAL/bash_profile" ] && source "$LOCAL/bash_profile"

# Just link the bash profile to .bashrc
# Link .bashrc second because it may depend on the login setup of
# the .bash_profile or .profile files
[ -f ~/.bashrc ] && source ~/.bashrc
