export BASH_PROFILE="$HOME/.bash_profile"

if [ -f ~/.local/bash_profile ]; then
    . ~/.local/bash_profile
fi

if [ -f ~/.profile ]; then
    . ~/.profile
fi

if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi
