set nocompatible
filetyp plugin on

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'terryma/vim-multiple-cursors'
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
Plug 'airblade/vim-gitgutter'
Plug 'tell-k/vim-autopep8'
Plug 'tpope/vim-fugitive'
Plug 'aserebryakov/vim-todo-lists'
Plug 'preservim/nerdtree'
call plug#end()

filetype plugin indent on

" FZF configuration
nmap <C-p> :FZF<CR>
imap <C-p> <C-o>:FZF<CR>

filetype plugin on
syntax on
filetype plugin indent on
colorscheme slate
set modelines=1
set number
set visualbell
set ruler
set encoding=utf-8
set wrap
set textwidth=0
set formatoptions=tcqrn1
set tabstop=4
set shiftwidth=4
set expandtab
set showmode
set showcmd
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set listchars=trail:·,nbsp:⎵,eol:¬,tab:▸\ ,extends:>,precedes:<
set list
set matchpairs+=<:>
set hidden
set wildmenu
set exrc
set paste
set wildignore+=**/node_modules/**,*.pyc,*.o,
" Specify python3 executable for some extension?
let g:python3_host_prog = "/usr/local/bin/python3"
" Forces block cursor for some terminals that don't have it already
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

imap <C-j> <C-o>j
imap <C-k> <C-o>k
imap <C-h> <C-o>h
imap <C-l> <C-o>l
nmap ; :
" Open nerd tree
nnoremap <Leader>b :NERDTree<CR>
" Open :ls and enter :b to start typing searched buffer
nnoremap gb :ls<cr>:b<space>
" Automatically save sessions on exit
au VimLeave * :mksession! /tmp/Session.vim
" Restore session using a command
nnoremap <Leader>ss :source /tmp/Session.vim<CR>

au FileType todo nnoremap<buffer> <Leader>N :VimTodoListsCreateNewItemAbove<CR>
au FileType todo nnoremap<buffer> <Leader>n :VimTodoListsCreateNewItemBelow<CR>
