syntax on
filetype plugin on
filetype plugin indent on
colorscheme slate
hi MatchParen cterm=none ctermbg=darkgray ctermfg=blue

let mapleader=' '

set nocompatible
set cursorline
set number
set relativenumber
set visualbell
set encoding=utf-8
set wrap
set formatoptions=tcqrn1
set tabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set listchars=trail:·,nbsp:⎵,eol:¬,tab:▸\ ,extends:>,precedes:<,nbsp:·
set list
set matchpairs+=<:>
set hidden
set wildmenu
set foldmethod=indent
set foldlevel=4
set wildignore+=**/node_modules/**,*.pyc,*.o,
set clipboard^=unnamed,unnamedplus
set completeopt=menu,menuone,preview
set novisualbell

" Forces block cursor for some terminals that don't have it already
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

" Add syntax highlighting to zsh/bash and generic .aliases files
augroup aliases
    au!
    au BufReadPost .aliases set syntax=bash
    au BufReadPost .zsh_aliases set syntax=zsh
    au BufReadPost .bash_aliases set syntax=bash
augroup end

" Naviagte windows in normal mode by holding ctrl
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
inoremap <C-j> <c-o><C-w>j
inoremap <C-k> <c-o><C-w>k
inoremap <C-h> <c-o><C-w>h
inoremap <C-l> <c-o><C-w>l

" Open file explorer and set explorer size to 40 characters
nnoremap <leader>b :vs `pwd`<cr>40<c-w>|
" Shortcut search for beginnig of word
nnoremap gw /\<
nnoremap gW ?\<
" Open :ls and enter :b to start typing searched buffer
nnoremap gb :ls<cr>:b<space>
" Replace word under cursor
nnoremap <leader>r g*Ncgn
" Search and replace the word under the cursor
nnoremap <leader>R :%s/<C-r><C-w>//g<left><left>
" Search and replace the current visual selection
vnoremap <leader>r ygv:s/<c-r>"//<left>

nnoremap <S-s> :w<cr>
nnoremap <S-q> :q<cr>
nnoremap <S-w> :bd<cr>

" Abbreviation to save and close current buffer
cnorea wd w\|bd
