# ~/.zprofile: executed by zsh for login shells
export SOURCED="${(%):-%x}:$SOURCED"

export PROMPT="%F{blue}%n%F{green}:%F{cyan}%~%F{green}$ %F{reset}"
export LOCAL="$HOME/.local"
export EDITOR=nvim
[ -d "$LOCAL/bin" ] && export PATH="$LOCAL/bin:$PATH"

# Setup some brew stuff
[ -f '/opt/homebrew/bin/brew' ] && eval "$(/opt/homebrew/bin/brew shellenv)"

# NPM setup
if command -v npm &> /dev/null; then
    export NPM_PREFIX="$HOME/.local/npm"
    if [[ ! "$(npm config get prefix)" == "$NPM_PREFIX" ]]; then
        echo "npm is installed: Setting install directory to $NPM_PREFIX" >&2
        npm config set prefix "$NPM_PREFIX"
    fi
    # Add globally installed packages to PATH
    export PATH="$(npm config get prefix)/bin:$PATH"
    # Also add all npm_modules executables to path
    export PATH="./npm_modules/bin:$PATH"
fi


[ -f "$LOCAL/zprofile" ] && source "$LOCAL/zprofile"
[ -f "~/.zshrc" ] && source "~/.zshrc"

