# Mark zshenv as sourced
export ZSHENV="${(%):-%x}:$ZSHENV"
export SOURCED="${(%):-%x}:$SOURCED"

export LOCAL="$HOME/.local"
export EDITOR=nvim
export HISTFILE=~/.zsh_history
export HISTSIZE=1000
export SAVEHIST=1000

if [ -f "$LOCAL/zshenv" ]; then
    source "$LOCAL/zshenv"
fi
