export ZSHRC="${(%):-%x}:$ZSHRC"
export SOURCED="${(%):-%x}:$SOURCED"

# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi
# Essential
source ~/.zplug/init.zsh
# Make sure to use double quotes to prevent shell expansion
# zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi
zplug load

bindkey '^F' autosuggest-accept
bindkey '^R' history-incremental-search-backward

setopt auto_cd
setopt append_history

export PROMPT="%F{blue}%n%F{green}:%F{cyan}%~%F{green}$ %F{reset}"

# NPM setup
if command -v npm &> /dev/null; then
    export NPM_PREFIX="$HOME/.local/npm"
    if [[ ! "$(npm config get prefix)" == "$NPM_PREFIX" ]]; then
        echo "npm is installed: Setting install directory to $NPM_PREFIX" >&2
        npm config set prefix "$NPM_PREFIX"
    fi
    # Add globally installed packages to PATH
    export PATH="$(npm config get prefix)/bin:$PATH"
    # Also add all npm_modules executables to path
    export PATH="./npm_modules/bin:$PATH"
fi

if [ -f "~/.zsh_aliases" ]; then
    source ~/.zsh_aliases
fi

if [ -f "~/.aliases" ]; then
    source ~/.aliases
fi

if [ -f "$LOCAL/zshrc" ]; then
    source "$LOCAL/zshrc"
fi
