# ~/.zshrc: executed by zsh(1) for non-login shells.
export SOURCED="${(%):-%x}:$SOURCED"

# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi
# Essential
source ~/.zplug/init.zsh
# Make sure to use double quotes to prevent shell expansion
# zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi
zplug load

bindkey '^F' autosuggest-accept
bindkey '^R' history-incremental-search-backward

HISTFILE=~/.zsh_history
HISTSIZE=2000
SAVEHIST=1000
setopt append_history
setopt auto_cd

if [ -f ~/.zsh_aliases ]; then
    source ~/.zsh_aliases
fi

if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

if [ -f "$LOCAL/zshrc" ]; then
    source "$LOCAL/zshrc"
fi
